// react-keycloak/src/App.js
import React from 'react';
import logo from './logo.svg';
import keycloaklogo from './keycloak.png';
import love from './heart.png';

import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
      <h1>Welcome to your Secure React App with Keycloak</h1>
      <div>
        <img src={logo} className="App-logo" alt="logo" />
        <img src={love} className="Love-logo" alt="heart" />
        <img src={keycloaklogo} className="Keycloak-logo" alt="keycloaklogo" />
        </div>
       
        <a
          className="App-link"
          href="https://medium.com/keycloak"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Keycloak
        </a>
      </header>
    </div>
  );
}

export default App;

// angular-keycloak/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'your Secure Angular with Keycloak';
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
  
  <img width="100" src="./assets/heart.png" alt="heart.png">
  <img width="260" src="./assets/keycloak.png" alt="keycloak.png" style="margin-left:10px">
 
</div>
<div style="text-align:center">
<p> For learning about keycloak<br>
  check out the
  <a href="https://medium.com/keycloak" target="_blank" rel="noopener">keycloak</a></p>
</div>
<router-outlet></router-outlet>
